/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication7;

import java.util.ArrayList;

/**
 *
 * @author lucia
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents(); // Inicio al componente
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(319, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(271, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            
        /**
         * Creo un array primero para listar las especialidades
     */
        
            ArrayList <Especialidad> especialidades = new ArrayList<>();        // Creo un ArrayList         
        
            Profesional profesion = new Profesional("3644332196","MARTE"     // Creo un objeto Profesional
                    ,"asdhotmail.com","Chapatin"
                    ,"Gomez",'M',"20/2/200",13434);
            
            Profesional profesiontwo = new Profesional("3644332196","MARTE"
                    ,"asdhotmail.com","Chapatin"
                    ,"Parra",'M',"20/2/200",42276444);
        
            
            /**
      Instanciio los profesionales 
     */
            
            
            
            
            
            Especialidad espe1 = new Especialidad("Radiologia",191 , profesion);
            Especialidad espe2 = new Especialidad("Psiquiatria" , 200 , profesiontwo);
            Especialidad espe3 = new Especialidad("Radiologia" , 191 , profesiontwo);
         
            
                  /**
     Instancio las especialidades
     */
            
            
            especialidades.add(espe1);       
            especialidades.add(espe2);
            
                  /**
     Las agregos a la lista
     * 
     * 
     * 
     */
                  
                  
                  
             /**
     Creo los pacientes
     */           
           Paciente paciente1 =  new Paciente(1
                   ,233152,"INSSSEP","Barrio Rucci",98
                   ,"Luciano","Marti",'M',"07-02-2000",42276444);
           
           Paciente paciente2 =  new Paciente(1
                   ,233152,"INSSSEP","Barrio Rucci",23
                   ,"Giordano","Marti",'M',"07-02-2000",42276444);
           
           Secretaria secre1 = new Secretaria(1
                   ,"Guardia","Marisa"
                   ,"Hernandez",'F',"02-02-2000",42276444);
           
           Secretaria secre2 = new Secretaria(1
                   ,"Guardia","Maria"
                   ,"Hernandez",'F',"02-02-2000",42276444);
           
                 /**
     Cargo el turno generado
     */ 
           
            espe1.cargarTurnos(new Turno(espe1.getProfesional(),"8:20 am" 
                    ,paciente1,1,secre1,"12/09/2023" ));
          
            espe1.cargarTurnos(new Turno (espe2.getProfesional(),"8:10 am" , paciente2 ,2, secre2 , "12/09/2023"));      
            
            
            
                  /**
     Uso un bucle foreach para recorrer los turnos y filtrar por fecha a los pacientes y los nro de turnos que pertenecen
     */
            
            for ( Turno i : espe1.getTurnos()) {   
                if (i.getFecha() == "12/09/2023"){
                System.out.println("El numero de turno es :" + i.getNroTurno() +
                "Y el nombre de la secretaria que lo agendo es : " + i.getSecre().getNombre() + "y su apellido es : " + i.getSecre().getApellido());}
                
            }
              /**
     Utilizo otro for each y si se da lacondicon inicio otro for each pero en el objeto turno para listarlos.
     */
          System.out.println("-------------------------");  
              
            
            for (Especialidad i : especialidades){
               for (Turno j : i.getTurnos()){
                    if(j.getProfesional().getDocumento() == 42276444 && i.getNro_especialidad() == 191){
                       System.out.println("El numero de turnos es " + j.getNroTurno() 
                       + "y la secretaria que agendo es > : " + j.getSecre().getNombre());
                    }
               
                   
                
            }
            
            
            System.out.println("-------------------------");  
          /**
           * Uso un for each para listar especialidades y dentro de especialiades uso otro bucle for 
           each para listar los turnos y filtrar por obra social. 
     */        
            
            for (Especialidad h : especialidades){
                    for (Turno j : h.getTurnos()){
                      if  (j.getNombrePaciente().getObraSocial() == "INSSSEP" && j.getNombrePaciente().getEdad() > 65){
                          System.out.println("Nombre de paciente : " + j.getNombrePaciente().getNombre());
                      }
                    }}

           
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
